#!/usr/bin/env node
/**
 * Download BisBeard's current CoA stat-weight module and generate Bestow data.
 *
 * The importer intentionally fails closed: all 70 Bestow specs must match exactly
 * once before any generated file is replaced.
 */

import { createHash } from "node:crypto";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const SITE = "https://coa.bisbeard.com";
const EXPECTED_PROFILE_COUNT = 70;

const sourceClassAliases = {
  "Blood Mage": "Bloodmage",
  Tinkerer: "Tinker",
};

const sourceSpecAliases = {
  "Venomancer|Rot": "Rotweaver",
};

function matchAsset(text, expression, label) {
  const match = text.match(expression);
  if (!match) throw new Error(`Could not locate ${label}`);
  const asset = match.slice(1).find(Boolean) || match[0];
  return new URL(asset, `${SITE}/`).href;
}

async function fetchText(url) {
  const response = await fetch(url, {
    headers: {"user-agent": "Bestow stat-weight importer"},
  });
  if (!response.ok) throw new Error(`${url} returned HTTP ${response.status}`);
  return response.text();
}

function luaString(value) {
  return `"${String(value).replaceAll("\\", "\\\\").replaceAll('"', '\\"')}"`;
}

function luaNumber(value) {
  if (!Number.isFinite(value)) throw new Error(`Invalid numeric weight: ${value}`);
  return Number(value).toString();
}

function parseBestowSpecs(classesLua) {
  const classBlocks = [...classesLua.matchAll(
    /^\s*([A-Z][A-Z0-9]*)\s*=\s*\{name\s*=\s*"([^"]+)".*?specs\s*=\s*\{(.*?)\}\s*\},?\s*$/gms,
  )];
  const specs = [];
  for (const block of classBlocks) {
    const [, classToken, className, specText] = block;
    for (const match of specText.matchAll(/\{(\d+),"([^"]+)","[A-Z]",\{[^}]*\}\}/g)) {
      specs.push({id: Number(match[1]), name: match[2], classToken, className});
    }
  }
  return specs;
}

function findProfiles(moduleExports) {
  for (const value of Object.values(moduleExports)) {
    if (!value || typeof value !== "object" || Array.isArray(value)) continue;
    const entries = Object.entries(value);
    if (entries.length !== EXPECTED_PROFILE_COUNT) continue;
    if (entries.every(([key, profile]) =>
      key.includes("|") &&
      profile && typeof profile === "object" &&
      Array.isArray(profile.anchors) &&
      profile.anchorWeights && typeof profile.anchorWeights === "object" &&
      profile.weights && typeof profile.weights === "object"
    )) return value;
  }
  throw new Error(`Could not identify the ${EXPECTED_PROFILE_COUNT}-profile export`);
}

function resolveProfiles(bestowSpecs, profiles) {
  const resolved = [];
  const used = new Set();
  for (const spec of bestowSpecs) {
    const sourceClass = sourceClassAliases[spec.className] || spec.className;
    const sourceSpec = sourceSpecAliases[`${spec.className}|${spec.name}`] || spec.name;
    const sourceKey = `${sourceClass}|${sourceSpec}`;
    const profile = profiles[sourceKey];
    if (!profile) throw new Error(`No BisBeard profile for Bestow spec ${spec.id} (${sourceKey})`);
    for (const [weight, value] of Object.entries(profile.weights)) {
      if (!Number.isFinite(value)) throw new Error(`Non-numeric ${sourceKey} weight ${weight}`);
    }
    if (!profile.anchors.length) throw new Error(`No normalization anchor for ${sourceKey}`);
    if (used.has(sourceKey)) throw new Error(`BisBeard profile matched twice: ${sourceKey}`);
    used.add(sourceKey);
    resolved.push({...spec, sourceKey, profile});
  }
  const unused = Object.keys(profiles).filter(key => !used.has(key));
  if (unused.length) throw new Error(`Unmatched BisBeard profiles: ${unused.join(", ")}`);
  return resolved.sort((a, b) => a.id - b.id);
}

function buildLua(resolved, metadata) {
  const lines = [
    "local _, CBC = ...",
    "",
    "-- Generated by scripts/extract_bisbeard_weights.mjs.",
    "-- Do not hand-edit; rerun the importer and review the source metadata.",
    "CBC.StatWeightSource = {",
    `  site=${luaString(SITE)},`,
    `  moduleURL=${luaString(metadata.moduleURL)},`,
    `  sha256=${luaString(metadata.sha256)},`,
    `  retrievedUTC=${luaString(metadata.retrievedUTC)},`,
    `  profileCount=${resolved.length},`,
    "}",
    "",
    "CBC.StatWeightsBySpecID = {",
  ];
  for (const item of resolved) {
    const weights = Object.entries(item.profile.weights).sort(([a], [b]) => a.localeCompare(b));
    lines.push(`  [${item.id}] = {`);
    lines.push(`    sourceKey=${luaString(item.sourceKey)}, role=${luaString(item.profile.role || "")},`);
    lines.push("    weights={");
    for (const [key, value] of weights) lines.push(`      ${key}=${luaNumber(value)},`);
    lines.push("    },");
    lines.push("  },");
  }
  lines.push("}", "");
  return lines.join("\n");
}

function csvCell(value) {
  const text = String(value ?? "");
  return /[",\r\n]/.test(text) ? `"${text.replaceAll('"', '""')}"` : text;
}

function buildCSV(resolved) {
  const weightKeys = [...new Set(resolved.flatMap(item => Object.keys(item.profile.weights)))].sort();
  const header = ["spec_id", "class_token", "class_name", "spec_name", "source_key", "role", ...weightKeys];
  const rows = [header];
  for (const item of resolved) {
    rows.push([
      item.id, item.classToken, item.className, item.name, item.sourceKey,
      item.profile.role || "",
      ...weightKeys.map(key => item.profile.weights[key] ?? ""),
    ]);
  }
  return rows.map(row => row.map(csvCell).join(",")).join("\n") + "\n";
}

async function main() {
  const homepage = await fetchText(`${SITE}/`);
  const mainURL = matchAsset(homepage, /(?:src=")?(\/?assets\/index-[^"']+\.js)/, "main JavaScript bundle");
  const mainBundle = await fetchText(mainURL);
  const moduleURL = matchAsset(
    mainBundle,
    /["'](\.?\/?assets\/specRoles-[^"']+\.js)["']|["'](\.\/specRoles-[^"']+\.js)["']/,
    "specRoles module",
  );
  const moduleText = await fetchText(moduleURL);
  const sha256 = createHash("sha256").update(moduleText).digest("hex");
  const retrievedUTC = new Date().toISOString();

  const temp = await mkdtemp(join(tmpdir(), "bestow-bisbeard-"));
  try {
    const modulePath = join(temp, "specRoles.mjs");
    await writeFile(modulePath, moduleText, "utf8");
    const moduleExports = await import(`${pathToFileURL(modulePath).href}?sha=${sha256}`);
    const profiles = findProfiles(moduleExports);
    const classesLua = await readFile(join(ROOT, "Data", "Classes.lua"), "utf8");
    const bestowSpecs = parseBestowSpecs(classesLua);
    if (bestowSpecs.length !== EXPECTED_PROFILE_COUNT) {
      throw new Error(`Parsed ${bestowSpecs.length} Bestow specs; expected ${EXPECTED_PROFILE_COUNT}`);
    }
    const resolved = resolveProfiles(bestowSpecs, profiles);
    const metadata = {site: SITE, mainURL, moduleURL, sha256, retrievedUTC, profileCount: resolved.length};

    await writeFile(join(ROOT, "Data", "StatWeights.lua"), buildLua(resolved, metadata), "utf8");
    await writeFile(join(ROOT, "docs", "bisbeard_stat_weights.csv"), buildCSV(resolved), "utf8");
    await writeFile(
      join(ROOT, "docs", "bisbeard_stat_weights_source.json"),
      JSON.stringify(metadata, null, 2) + "\n",
      "utf8",
    );
    console.log(`Generated ${resolved.length} profiles from ${moduleURL}`);
    console.log(`SHA-256 ${sha256}`);
  } finally {
    await rm(temp, {recursive: true, force: true});
  }
}

await main();
